### ISSUE TITLE
BUG 1.20.4 source code isn't buildable

### ISSUE THREAD

**Issue by ghost** [Nooniboi/Public-Ikea#6]
**Describe the bug**
If I download the 1.20.4 source code, open the folder in command promt and run gradlew build, it says 
![Screenshot 2024-09-27 091040](https://github.com/user-attachments/assets/e089ea82-7d2d-469d-801e-b52721d920eb)

**To Reproduce**
Download 1.20.4 source code, open folder in command prompt and run gradlew build

**Expected behavior**
I expected it to build into the .ajr file

**Screenshots**

**Desktop (please complete the following information):**
 - Windows: 
 - 10:
- Fabric Api version: not relevant
 - Other mods used: not relevant

**Additional context**
Ikea Addon is a nice addon, but because it doesn't build I can't edit the code. Please fix it

**Comment by Nooniboi** [comment]
> **Describe the bug** If I download the 1.20.4 source code, open the folder in command promt and run gradlew build, it says ![Screenshot 2024-09-27 091040](https://private-user-images.githubusercontent.com/182807242/371431606-e089ea82-7d2d-469d-801e-b52721d920eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MDU5NTksIm5iZiI6MTcyNzgwNTY1OSwicGF0aCI6Ii8xODI4MDcyNDIvMzcxNDMxNjA2LWUwODllYTgyLTdkMmQtNDY5ZC04MDFlLWI1MjcyMWQ5MjBlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxODAwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGVmYjkwNjVlYTEwNGZkZTdlYjgwMGJlN2YxZTVlMjRlYjUxZTI4Zjc4ZjU4YjllOTYxNDg4YWM1NTQ4YTI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.C5xhQDEN6YSaYMjlIG8d6rhmwn8gUTjXgc1pe0-jqTI)
> 
> **To Reproduce** Download 1.20.4 source code, open folder in command prompt and run gradlew build
> 
> **Expected behavior** I expected it to build into the .ajr file
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * Windows:
> * 10:
> * Fabric Api version: not relevant
> * Other mods used: not relevant
> 
> **Additional context** Ikea Addon is a nice addon, but because it doesn't build I can't edit the code. Please fix it

Hi! this error is not a bug in the source code but most likely an error related to using wrong java version with gradle.

i highly recommend you search this error as there is different resolutions to this error.
